"""empty message

Revision ID: 5826369480b3
Revises: 8ad4654a1998
Create Date: 2020-12-20 23:23:40.010175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5826369480b3'
down_revision = '8ad4654a1998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('dt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'dt')
    # ### end Alembic commands ###
