"""empty message

Revision ID: d7faa821b27d
Revises: 615fe983a7ce
Create Date: 2020-12-21 14:51:20.682511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7faa821b27d'
down_revision = '615fe983a7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_desc')
    # ### end Alembic commands ###
